# Project: Prj_Calculadora_Avan
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe -D__DEBUG__
CC       = gcc.exe -D__DEBUG__
WINDRES  = windres.exe
OBJ      = main.o testeNum.o calculadora.o
LINKOBJ  = main.o testeNum.o calculadora.o
LIBS     = -L"C:/Users/lucas.damasceno/Desktop/Dev-Cpp/MinGW64/lib" -L"C:/Users/lucas.damasceno/Desktop/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc -g3
INCS     = -I"C:/Users/lucas.damasceno/Desktop/Dev-Cpp/MinGW64/include" -I"C:/Users/lucas.damasceno/Desktop/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/lucas.damasceno/Desktop/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/Users/lucas.damasceno/Desktop/Dev-Cpp/MinGW64/include" -I"C:/Users/lucas.damasceno/Desktop/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/lucas.damasceno/Desktop/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Users/lucas.damasceno/Desktop/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = Prj_Calculadora_Avan.exe
CXXFLAGS = $(CXXINCS) -g3
CFLAGS   = $(INCS) -g3
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)

testeNum.o: testeNum.cpp
	$(CPP) -c testeNum.cpp -o testeNum.o $(CXXFLAGS)

calculadora.o: calculadora.cpp
	$(CPP) -c calculadora.cpp -o calculadora.o $(CXXFLAGS)
